### ISSUE TITLE
About Data Annotation Tools

### ISSUE THREAD

**Issue by mingliangzhang2018** [lupantech/InterGPS#2]
Excuse me，how can I use the Data Collection tool? When I run app.py,  it gets results 
![image](https://user-images.githubusercontent.com/38106776/127290825-cb909aec-5a15-4c80-977d-b650c518ff35.png)
but without anything in the web link. 
Best wish!

**Comment by lupantech** [comment]
Thanks for your comments.
After running the app.py, **click** the [http://localhost:5000/](http://localhost:5000/) link on the terminal and the annotating page will show on the browser. Or, you can copy the URL link to the browser address and open it.

**Comment by mingliangzhang2018** [comment]
Thank you very much, I solved the problem.
