### ISSUE TITLE
About datasets 

### ISSUE THREAD

**Issue by mingliangzhang2018** [lupantech/InterGPS#4]
Hello, how can I expand the data set of  Geometry3K？ Where the  math geometry problems of Geometry3K come from? Could you please provide more specific web links or other information? 
Thank you very much!

**Comment by lupantech** [comment]
To expand the dataset, you can use the annotation tool the project provides to collect new problem data. Problems in Geometry3K are collected from two textbooks as introduced in the [paper](https://arxiv.org/abs/2105.04165). Make sure you have fair access to the online resources before you collect the problems.
