### ISSUE TITLE
DataSet Generation

### ISSUE THREAD

**Issue by Akshat188** [lupantech/InterGPS#9]
Hi Pan,
Loved your work in InterGPS. We were planning to extend the dataset, using the annotation tools shared. We wanted to know in logic_form.json for each question (Ground Truth), how was point positions added was this done manually or using some subroutine?
Thanks, Akshat

**Comment by lupantech** [comment]
Hi,
Thanks so much for your interest in our work! We provided the point positions in the logic_form.json. These positions were automatically recognized by our developed diagram parser. They were further manually checked and edited via the shared [data collection tool](https://github.com/lupantech/InterGPS#data-collection).
Bests, Pan
